{{- if and .Values.config.oidc.enabled .Values.config.oidc.clientSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gatekeeper-policy-manager.fullname" . }}-oidc
  labels:
    {{- include "gatekeeper-policy-manager.labels" . | nindent 4 }}
stringData:
  clientSecret: {{ .Values.config.oidc.clientSecret }}
{{- end -}}