{{- if .Values.config.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gatekeeper-policy-manager.fullname" . }}
  labels:
    {{- include "gatekeeper-policy-manager.labels" . | nindent 4 }}
stringData:
  secretKey: {{ required "A valid .Values.config.secretKey entry required! Choose a secure string" .Values.config.secretKey | quote }}
{{- end }}
