{{- if .Values.config.multiCluster.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gatekeeper-policy-manager.fullname" . }}-multicluster
  labels:
    {{- include "gatekeeper-policy-manager.labels" . | nindent 4 }}
data:
  kubeconfig: {{ .Values.config.multiCluster.kubeconfig | b64enc }}
{{- end -}}